Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/kevin_lucas/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/esptool/__main__.py", line 9, in <module>
    esptool._main()
  File "/home/kevin_lucas/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1314, in _main
    main()
  File "/home/kevin_lucas/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/esptool/__init__.py", line 1036, in main
    operation_func(esp, args)
  File "/home/kevin_lucas/.espressif/python_env/idf5.4_py3.12_env/lib/python3.12/site-packages/esptool/cmds.py", line 491, in write_flash
    if set_flash_size and set_flash_size > flash_end:
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '>' not supported between instances of 'int' and 'NoneType'
CMake Error at run_serial_tool.cmake:67 (message):
  
  /home/kevin_lucas/.espressif/python_env/idf5.4_py3.12_env/bin/python;;/home/kevin_lucas/esp/v5.4/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



